
service: serverless-tienda-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

stages:
  default:


functions:
  customer:
    handler: src/infra/handlers/customer.handler
    environment: 
      CUSTOMERS_TABLE: !Ref CustomersTable


# you can add CloudFormation resource templates here
resources:
  Resources:
    CustomersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: customers-table-${sls:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: customer_id
            AttributeType: S
        KeySchema:
          - AttributeName: customer_id
            KeyType: HASH

  Outputs:
    CustomersTableName:
      Description: "customers dynamodb table name"
      Value: !Ref CustomersTable
